/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 lujain_home.gltf 
*/


import  { useRef, useEffect, useState } from 'react';
import { useGLTF, PerspectiveCamera, useAnimations } from '@react-three/drei'


export default function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/lujain_home.gltf')
  const { actions } = useAnimations(animations, group)

/* useEffect(() => {
    actions['Animation'].play(); // Replace "Animation" with the name of your animation
}, [actions]);
  */
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);

  useEffect(() => {
    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    // Cleanup function to remove the event listener
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const [defaultCamera, setDefaultCamera] = useState(window.innerWidth < 768 ? 'camera' : 'camera1');
  console.log(defaultCamera);

  return (
    <group {...props} dispose={null}>
      <group position={[34.716, 30.562, -4.957]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397}>
        <mesh geometry={nodes.Cyber_Punk_Room_Material_0.geometry} material={materials['Material.001']} scale={[1.115, 1, 1]} />
      </group>
      <mesh geometry={nodes.Object_2.geometry} material={materials.object1_auv} position={[34.629, 31.234, -5.526]} rotation={[-1.348, 0, 0]} scale={0.013} />
      <group position={[35.148, 31.044, -4.352]} rotation={[-Math.PI / 2, 0, 3.138]} scale={0.397}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} position={[0.4, -0.047, -0.74]} rotation={[0, -0.886, 0]} />
        </group>
      </group>
      <group position={[34.158, 30.781, -4.957]} rotation={[-1.557, 0.038, -1.162]} scale={0.001}>
        <group position={[0.002, 0.004, 0.004]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.001, 0.006, 0.003]}>
            <group position={[-0.001, 50.46, -8.885]} rotation={[-1.943, 0, 0]} scale={100}>
              <mesh geometry={nodes.Cube001_Auto_03_0_1.geometry} material={materials.Auto_03} />
              <mesh geometry={nodes.Cube001_Auto_03_0_2.geometry} material={materials.Auto_04} />
            </group>
            <group position={[-72.229, -27.68, 35.454]} rotation={[-Math.PI / 2, 0, 0.002]} scale={100}>
              <mesh geometry={nodes.Keys_Auto_02_0_1.geometry} material={materials.Auto_02} />
              <mesh geometry={nodes.Keys_Auto_02_0_2.geometry} material={materials.Auto_01} />
              <mesh geometry={nodes.Keys_Auto_02_0_3.geometry} material={materials.Auto_03} />
              <mesh geometry={nodes.Keys_Auto_02_0_4.geometry} material={materials.Auto_04} />
            </group>
            <mesh geometry={nodes.laptop002.geometry} material={materials.Screen} position={[-0.001, 50.46, -8.885]} rotation={[-1.943, 0, -Math.PI / 2]} scale={100}   onClick={() => {
                      if (windowWidth < 768) {
                        setDefaultCamera(prevCamera => prevCamera === 'screen02' ? 'back3' : 'screen02');
                      } else {
                        setDefaultCamera(prevCamera => prevCamera === 'screen2' ? 'back1' : 'screen2');
                      }
                   }} onPointerOver={() => document.body.style.cursor = 'pointer'}
                   onPointerOut={() => document.body.style.cursor = 'auto'}/>
          </group>
        </group>
      </group>
      <group position={[34.716, 30.562, -4.957]} rotation={[Math.PI / 2, 0, 0]} scale={0.397}>
        <group position={[0, 228.549, 42.602]} rotation={[1.011, 0, 0]}>
          <mesh geometry={nodes.bow001.geometry} material={materials.material} position={[2242.436, 3106.938, -2232.378]} rotation={[1.637, 0.266, -0.483]} scale={1.24} />
        </group>
      </group>
      <group position={[34.581, 30.933, -5.333]} rotation={[3.13, -1.39, -0.016]} scale={0.397}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.material0000} position={[-0.038, -0.683, 0.444]} />
      </group>
      <group position={[34.401, 30.797, -4.814]} rotation={[-Math.PI / 2, 0, 0]} scale={0.069}>
        <mesh geometry={nodes.Object_2001.geometry} material={materials['Material.002']} position={[-7.273, 1.962, -2.715]} scale={0.908} />
      </group>
      <group position={[34.752, 30.956, -5.422]} rotation={[-Math.PI / 2, 0, -0.37]} scale={0.007}>
        <group position={[0.4, -0.148, 6.722]} rotation={[0, 0, -0.389]} scale={[3.404, 3.404, 0.186]}>
          <mesh geometry={nodes.Lid_0.geometry} material={materials['material.003']} position={[0, 0, -0.003]} />
        </group>
        <mesh geometry={nodes.Coffee_Coup_0.geometry} material={materials.Texture} position={[0.4, -0.148, 0.221]} rotation={[0, 0, -0.852]} />
      </group>
      <group position={[37.601, 2.252, -1.589]} rotation={[-Math.PI / 2, 0.045, -3.104]} scale={1.064}>
        <group position={[-0.085, 0.021, 0.004]} rotation={[-0.002, 0.014, -0.059]} scale={0.944}>
          <mesh geometry={nodes.Object_2002_1.geometry} material={materials.material_2} />
          <mesh geometry={nodes.Object_2002_2.geometry} material={materials.material_0} />
          <mesh geometry={nodes.Object_2002_3.geometry} material={materials.material_1} />
        </group>
      </group>
      <group position={[34.664, 30.935, -5.418]} rotation={[-Math.PI / 2, 0, 0]} scale={0.001}>
        <group position={[0, 0, 0.002]}>
          <mesh geometry={nodes.Object_2002.geometry} material={materials['Material.wooden-plate']} position={[0, 0, -0.867]} />
        </group>
      </group>
      <group position={[34.288, 31.205, -5.516]} rotation={[-Math.PI / 2, 0, 0]} scale={0.025}>
        <mesh geometry={nodes.Object_10.geometry} material={materials.blinn7SG} />
        <mesh geometry={nodes.Object_2003.geometry} material={materials.aiStandardSurface7SG} />
        <mesh geometry={nodes.Object_3001.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials.blinn4SG} />
        <mesh geometry={nodes.Object_5001.geometry} material={materials.blinn5SG} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.aiStandardSurface7SG} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.blinn2SG} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.blinn3SG} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.blinn6SG} />
      </group>
      <group position={[37.431, 2.309, -1.468]} rotation={[-Math.PI / 2, 0.035, 0]} scale={0.064}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.53, 0.649, -0.487]} rotation={[1.575, 0.331, -0.001]} scale={[0.029, 0.029, 0.032]}>
            <mesh geometry={nodes.Object_24.geometry} material={materials.material_6} position={[-0.002, 0, 0]} />
          </group>
          <group position={[0.322, 0.75, -0.484]} rotation={[1.575, 0.264, -0.001]} scale={[0.041, 0.041, 0.025]}>
            <mesh geometry={nodes.Object_26.geometry} material={materials.material_6} position={[-0.001, 0, 0]} />
          </group>
          <group position={[0.198, 0.712, -0.486]} rotation={[2.001, -0.201, 0.091]} scale={0.029}>
            <mesh geometry={nodes.Object_28.geometry} material={materials.material_6} position={[-0.001, 0, 0]} />
          </group>
          <group position={[0.135, 0.694, -0.374]} rotation={[1.83, 0.079, -0.535]} scale={0.029}>
            <mesh geometry={nodes.Object_30.geometry} material={materials.material_6} position={[0.001, -0.001, 0]} />
          </group>
          <group position={[0.19, 0.615, 0.743]} rotation={[1.283, 0.048, 2.979]} scale={[0.024, 0.024, 0.019]}>
            <mesh geometry={nodes.Object_34.geometry} material={materials.material_6} position={[-0.001, 0, 0]} />
          </group>
          <group position={[0.076, 0.618, 0.682]} rotation={[1.509, -0.325, 2.961]} scale={[0.029, 0.029, 0.032]}>
            <mesh geometry={nodes.Object_36.geometry} material={materials.material_6} position={[-0.001, 0.001, -0.001]} />
          </group>
          <group position={[0.255, 0.719, 0.599]} rotation={[1.521, -0.26, 2.965]} scale={[0.041, 0.041, 0.025]}>
            <mesh geometry={nodes.Object_38.geometry} material={materials.material_6} position={[0.001, 0, 0]} />
          </group>
          <group position={[0.377, 0.68, 0.58]} rotation={[1.178, 0.269, 3.073]} scale={0.029}>
            <mesh geometry={nodes.Object_40.geometry} material={materials.material_6} position={[-0.001, 0, 0]} />
          </group>
          <group position={[0.421, 0.663, 0.459]} rotation={[1.302, -0.035, 2.443]} scale={0.029}>
            <mesh geometry={nodes.Object_42.geometry} material={materials.material_6} position={[-0.002, -0.002, 0]} />
          </group>
          <group position={[0.583, 0.717, 0.579]} rotation={[1.469, 0.333, -3.12]} scale={[0.041, 0.041, 0.025]}>
            <mesh geometry={nodes.Object_44.geometry} material={materials.material_6} position={[-0.001, 0, 0.001]} />
          </group>
          <group position={[0.068, 2.394, -0.06]} rotation={[3.081, 0.401, 2.892]} scale={-0.106}>
            <mesh geometry={nodes.Object_12.geometry} material={materials.material_4} position={[-0.001, 0, 0]} />
          </group>
          <group position={[0.153, 0.437, -0.545]} rotation={[0.225, 1.396, -0.284]} scale={0.07}>
            <mesh geometry={nodes.Object_48001.geometry} material={materials['material_0.002']} position={[0, 0, -0.001]} />
          </group>
          <group position={[0.361, 0.494, -0.475]} rotation={[3.039, -1.184, 2.984]} scale={[0.057, 0.041, 0.057]}>
            <mesh geometry={nodes.Object_54001.geometry} material={materials['material_0.002']} position={[-0.001, 0, -0.001]} />
          </group>
          <group position={[0.014, 0.464, -0.523]} rotation={[-Math.PI, 0.215, -Math.PI]} scale={0.07}>
            <mesh geometry={nodes.Object_56001.geometry} material={materials['material_0.002']} position={[-0.001, 0, 0]} />
          </group>
          <group position={[0.215, 0.462, 0.597]} rotation={[0.179, 1.352, -0.237]} scale={[0.057, 0.041, 0.057]}>
            <mesh geometry={nodes.Object_66.geometry} material={materials['material_0.002']} position={[0, 0, -0.002]} />
          </group>
          <mesh geometry={nodes.Object_8001.geometry} material={materials['material_2.001']} position={[0.449, 1.866, -0.103]} rotation={[2.126, 0.08, 2.183]} scale={0.305} />
          <mesh geometry={nodes.Object_22.geometry} material={materials.material_6} position={[0.41, 0.646, -0.615]} rotation={[1.862, 0, 0]} scale={[0.024, 0.024, 0.019]} />
          <mesh geometry={nodes.Object_32.geometry} material={materials.material_6} position={[-0.005, 0.748, -0.519]} rotation={[1.729, -0.311, 0.199]} scale={[0.041, 0.041, 0.025]} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials['material_2.001']} position={[-0.014, 2.705, 0.072]} rotation={[1.433, 0.095, -0.008]} scale={0.498} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.material_4} position={[0.463, 1.747, -0.471]} rotation={[-2.768, 0.41, 2.992]} scale={-0.033} />
          <mesh geometry={nodes.Object_46.geometry} material={materials.material_7} position={[0.2, 0.47, -0.107]} rotation={[-2.974, 0.819, 3.069]} scale={[-0.144, -0.146, -0.132]} />
          <mesh geometry={nodes.Object_10001.geometry} material={materials.material_3} position={[0.371, 0.173, 0]} scale={[1.291, 0.334, 1.291]} />
          <mesh geometry={nodes.Object_4002.geometry} material={materials['material.004']} position={[0, 0.724, 0]} />
          <mesh geometry={nodes.Object_16.geometry} material={materials['material.004']} position={[0.001, 0.562, 0]} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.material_5} position={[0.001, 0.562, 0]} />
          <mesh geometry={nodes.Object_20.geometry} material={materials.material_5} position={[0, 0.724, 0]} />
          <mesh geometry={nodes.Object_50.geometry} material={materials['material_0.002']} position={[0.513, 0.529, -0.482]} scale={[0.07, 0.062, 0.07]} />
          <mesh geometry={nodes.Object_52.geometry} material={materials['material_0.002']} position={[0.566, 0.457, -0.749]} rotation={[0.225, 1.396, -0.284]} scale={[0.101, 0.05, 0.101]} />
          <mesh geometry={nodes.Object_58.geometry} material={materials.material_8} position={[-0.094, 0.461, -0.273]} rotation={[3.039, -1.184, 2.984]} scale={[0.101, 0.074, 0.101]} />
          <mesh geometry={nodes.Object_60001.geometry} material={materials['material_0.002']} position={[0.431, 0.406, 0.63]} rotation={[1.59, -1.532, 1.528]} scale={0.07} />
          <mesh geometry={nodes.Object_62.geometry} material={materials['material_0.002']} position={[0.066, 0.498, 0.63]} rotation={[Math.PI, -0.17, Math.PI]} scale={[0.07, 0.062, 0.07]} />
          <mesh geometry={nodes.Object_64001.geometry} material={materials['material_0.002']} position={[0.085, 0.426, 0.947]} rotation={[1.59, -1.532, 1.528]} scale={[0.101, 0.05, 0.101]} />
          <mesh geometry={nodes.Object_68.geometry} material={materials['material_0.002']} position={[0.565, 0.433, 0.585]} rotation={[0, -0.045, 0]} scale={0.07} />
          <mesh geometry={nodes.Object_70.geometry} material={materials['material_0.002']} position={[0.63, 0.43, 0.321]} rotation={[0.179, 1.352, -0.237]} scale={[0.101, 0.074, 0.101]} />
        </group>
      </group>
      <group position={[34.454, 30.973, -5.395]} rotation={[-2.327, 0, 0]} scale={0.225}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.button_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.coil_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.earpad_inside_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.earpads_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.earphone_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.side_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.softpart_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.stars_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.top_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.tribalbase_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
          <mesh geometry={nodes.tribals_low_M_Headphones_0.geometry} material={materials.M_Headphones} />
        </group>
      </group>
      <group position={[37.824, 2.303, -1.509]} rotation={[-1.619, 0.038, 0]} scale={0.038}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Circle_PolaroidCamera_0.geometry} material={materials['PolaroidCamera.001']} position={[-1.859, 3.55, 0.319]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[35.192, 31.052, -4.924]} rotation={[-1.7, 0, 0]} scale={0}>
        <group position={[0, -0.004, 0.027]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.031, 0.021, 0]}>
            <group position={[-8.781, 4.216, -0.004]} scale={[1, 1, 1.602]}>
              <group position={[2289.719, 464.196, -234.521]} rotation={[-1.306, -1.392, -1.592]}>
                <mesh geometry={nodes['Book_01_-_Default_0_1'].geometry} material={materials['01_-_Default.001']} />
                <mesh geometry={nodes['Book_01_-_Default_0_2'].geometry} material={materials['02_-_Default']} />
                <mesh geometry={nodes['Book_01_-_Default_0_3'].geometry} material={materials['03_-_Default']} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[33.784, 30.625, -5.449]} rotation={[-1.582, 0.443, -1.439]} scale={0.305}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -0.001, 0]}>
            <group position={[0, -0.001, 0]}>
              <group position={[0, -0.001, 0]}>
                <mesh geometry={nodes.FG_Acoustic_GuitarShape_AcousticGuitar_0.geometry} material={materials['AcousticGuitar.001']} position={[55.205, 19.084, -34.551]} rotation={[0.019, 0.597, 0.527]} />
              </group>
            </group>
          </group>
        </group>
      </group>
      <group position={[34.716, 30.562, -4.957]} rotation={[Math.PI / 2, 0, 0]} scale={0.397}>
        <mesh geometry={nodes.defaultMaterial013.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial012.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial011.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial010.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial009.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial008.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial007.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial006.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial005.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial004.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial003.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial002.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.defaultMaterial001.geometry} material={materials.lambert1} />
      </group>
      <group position={[34.043, 30.924, -4.648]} rotation={[-Math.PI / 2, 0, 0]} scale={0.02}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.016, 0, 0]}>
            <group position={[-0.016, 210.094, 0]}>
              <mesh geometry={nodes.KOLLAR001_Material022_0.geometry} material={materials['Material.022']} position={[1465.031, -923.375, 971.418]} rotation={[-0.854, -0.28, 0.975]} />
            </group>
          </group>
        </group>
      </group>
      <group position={[40.618, 4.922, -0.072]} rotation={[-0.129, -0.131, -0.013]} scale={2.056}>
        <group scale={18.723}>
          <mesh geometry={nodes.home.geometry} material={materials['Material.005']} position={[0.059, 0.289, 0.191]} scale={0.053} />
          <mesh geometry={nodes.Object_97.geometry} material={materials['Material.005']} position={[-0.548, 0.411, 0.126]} rotation={[0, -1.571, 0]} scale={0.053}  onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera('back');
    } else {
      setDefaultCamera('back1');
    }
 }} 
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'} />
        </group>
        <mesh geometry={nodes.Object_149.geometry} material={materials['Material.005']} position={[1.828, 18.384, 3]} rotation={[-Math.PI, 1.57, -Math.PI]} />
      </group>
      <group position={[34.419, 30.756, -4.209]} rotation={[-2.452, -0.363, 0.27]} scale={0.003}>
        <group position={[-0.001, -0.001, 0]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.002, 0, 0]}>
            <mesh geometry={nodes.Abalorio_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Accesorios_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Arrow_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 4.997]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Bow_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Cuerdas_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Leave_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Piedra_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.PiedraBig_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Plumas_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
            <mesh geometry={nodes.Vendas_low_Bow_0.geometry} material={materials['material.011']} position={[-0.002, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          </group>
        </group>
      </group>
      <PerspectiveCamera makeDefault={defaultCamera === 'back1'} far={100} near={0.1} fov={25.895} position={[33.103, 31.181, -3.115]} rotation={[-0.16, -0.687, -0.102]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'back'} far={100} near={0.1} fov={30.895} position={[32.9, 31.181, -3.115]} rotation={[-0.16, -0.687, -0.102]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'back3'} far={100} near={0.1} fov={30.895} position={[33.9, 31.181, -3.115]} rotation={[-0.16, -0.687, -0.102]} scale={0.397} />
      <pointLight intensity={0.162} decay={12} color="#ff7995" position={[34.338, 30.795, -5.063]} rotation={[-1.839, 0.602, 1.932]} scale={0.397} />


      <pointLight intensity={94.631} decay={5} color="#e68338" position={[35.223, 31.692, -4.91]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />
      <pointLight intensity={20.149} decay={3} color="#df78b9" position={[34.19, 31.556, -5.357]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />

      
    
    
      <pointLight intensity={0.0514} decay={8} position={[34.254, 30.984, -4.44]} rotation={[-Math.PI / 2, 0, 0]} scale={0.0003} />
    
      <spotLight intensity={3021.938} angle={0.875} penumbra={0.15} decay={20} color="#f12f17" position={[35.087, 32.118, -5.241]} rotation={[-Math.PI / 2, 0, 0]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'screen01'} far={100} near={0.1} fov={26.895} position={[34.802, 31.138, -4.46]} rotation={[-0.103, -1.144, -0.094]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'screen1'} far={100} near={0.1} fov={56.895} position={[34.802, 31.138, -4.46]} rotation={[-0.103, -1.144, -0.094]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'screen2'} far={100} near={0.1} fov={26.895} position={[33.792, 30.889, -4.626]} rotation={[-0.167, -0.759, -0.116]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'screen02'} far={100} near={0.1} fov={56.895} position={[33.792, 30.889, -4.626]} rotation={[-0.167, -0.759, -0.116]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'screen3'} far={100} near={0.1} fov={22.895} position={[34.315, 31.127, -4.854]} rotation={[-0.109, -0.403, -0.043]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'screen03'} far={100} near={0.1} fov={62.895} position={[34.315, 31.127, -4.854]} rotation={[-0.109, -0.403, -0.043]} scale={0.397} />
      <PerspectiveCamera makeDefault={defaultCamera === 'camera'} far={1000} near={0.1} fov={52.895} position={[-11.226, -0.166, 72.563]} rotation={[0.444, -0.558, 0.247]} />
      <PerspectiveCamera makeDefault={defaultCamera === 'camera1'} far={1000} near={0.1} fov={32.895} position={[-11.226, -0.166, 72.563]} rotation={[0.444, -0.558, 0.247]} />
      <mesh geometry={nodes.Object_92.geometry} material={materials.BAse_esxport_transparent} />
      <mesh geometry={nodes.Object_92001.geometry} material={materials['BAse_esxport_transparent.001']} />
      <mesh geometry={nodes.screen01001.geometry} material={nodes.screen01001.material} position={[35.317, 31.114, -4.688]} rotation={[0, 0, 1.139]} scale={0.059} onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera(prevCamera => prevCamera === 'screen1' ? 'back' : 'screen1');
    } else {
      setDefaultCamera(prevCamera => prevCamera === 'screen01' ? 'back1' : 'screen01');
    }
 }}
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
      <mesh geometry={nodes.comp.geometry} material={nodes.comp.material} position={[34.79, 30.94, -5.736]} rotation={[1.613, -0.016, 0.001]} scale={0.026} onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera(prevCamera => prevCamera === 'screen03' ? 'back' : 'screen03');
    } else {
      setDefaultCamera(prevCamera => prevCamera === 'screen3' ? 'back1' : 'screen3');
    }
 }}
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
    </group>
  )
}

useGLTF.preload('/lujain_home.gltf')
