/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 maram03.gltf 
*/

import {useEffect, useState } from 'react';
import { useGLTF, PerspectiveCamera } from '@react-three/drei'
//import { useThree, useFrame } from '@react-three/fiber';


export default function Model(props) {
  //const group = useRef()
  const { nodes, materials } = useGLTF('/maram03.gltf')
  //const { actions } = useAnimations(animations, group)
  
  const [windowWidth, setWindowWidth] = useState(window.innerWidth);
 //console.log(animations.map(animation => animation.name));

  useEffect(() => {
    const handleResize = () => setWindowWidth(window.innerWidth);
    window.addEventListener('resize', handleResize);
    // Cleanup function to remove the event listener
    return () => window.removeEventListener('resize', handleResize);
  }, []);

  const [defaultCamera, setDefaultCamera] = useState(window.innerWidth < 768 ? 'camera' : 'camera1');
  //console.log(defaultCamera);

  return (
    <group {...props} dispose={null}>
      <group position={[-13.723, -10.112, -75.254]} rotation={[-Math.PI / 2, 0, 0]} scale={3.826}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-170.285, 1166.761, 1098.535]} rotation={[0, 1.569, 0]} scale={0.314}>
            <group position={[49.169, 0.004, -7.854]}>
              <mesh geometry={nodes['Mause_Monitor&Mouse_0'].geometry} material={materials.MonitorMouse} position={[-16.706, 0, -27.962]} />
            </group>
            <group position={[-1.268, 25.409, -45.481]} rotation={[Math.PI / 2, 0, 0]}>
              <mesh geometry={nodes['Monitor001_Monitor&Mouse_0'].geometry} material={materials.MonitorMouse} position={[-0.026, -19.153, -0.001]} />
            </group>
            <group position={[50.946, 25.409, -30.313]} rotation={[Math.PI / 2, 0, 0.582]} scale={0.01}>
              <mesh geometry={nodes['Monitor002_Monitor&Mouse_0'].geometry} material={materials.MonitorMouse} position={[-1055.297, -1598.324, -0.033]} />
            </group>
            <group position={[-52.947, 25.409, -29.892]} rotation={[Math.PI / 2, 0, -0.606]} scale={0.01}>
              <mesh geometry={nodes['Monitor003_Monitor&Mouse_0'].geometry} material={materials.MonitorMouse} position={[1089.383, -1575.299, 0.007]} />
            </group>
            <mesh geometry={nodes.KeyBoard_Keyboard_0.geometry} material={materials.Keyboard} position={[-9.293, 0, -24.537]} />
          </group>
          <group position={[-150.977, 1141.594, 1098.557]} rotation={[Math.PI / 2, 0, 1.572]} scale={0.314}>
            <group position={[0.027, 19.748, 0]} rotation={[0, 0, 1.286]}>
              <mesh geometry={nodes.OfficeChair_OfficeChair_0_1.geometry} material={materials.OfficeChair} />
              <mesh geometry={nodes.OfficeChair_OfficeChair_0_2.geometry} material={materials.Tables} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-20.796, -9.881, -74.958]} rotation={[-Math.PI / 2, 0, -2.097]} scale={0.615}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.001, 0, 0.001]}>
            <group position={[699.421, 50.364, -354.913]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh geometry={nodes.BigBoy_blackbutton1_BigBoy_0.geometry} material={materials.BigBoy} position={[50.932, 30.07, 70.284]} rotation={[0, 0, -2.88]} scale={0.29} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-14.701, 34.036, -33.22]} rotation={[-Math.PI / 2, 0, -1.544]} scale={1.787}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial002.geometry} material={materials['1004']} />
          <mesh geometry={nodes.defaultMaterial004.geometry} material={materials['1005']} />
          <mesh geometry={nodes.defaultMaterial005.geometry} material={materials['1003']} position={[0.028, 0, -0.001]} />
          <mesh geometry={nodes.defaultMaterial006.geometry} material={materials['1006']} />
          <mesh geometry={nodes.defaultMaterial007.geometry} material={materials['1002']} position={[0, 0, -0.002]} />
        </group>
      </group>
      <group position={[-17.415, 33.631, -31.776]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.004, 0.015, 0.007]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, 0]}>
            <group position={[0, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh geometry={nodes.Cube_low_table_scifi_0.geometry} material={materials.table_scifi} position={[2.044, 0.5, -0.067]} scale={[1.394, 0.896, 0.671]} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-19.983, 33.632, -29.425]} rotation={[-Math.PI / 2, 0, 2.334]} scale={0.025}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={41.722}>
            <mesh geometry={nodes.Object047_Piano_0_1.geometry} material={materials['Piano.001']} />
            <mesh geometry={nodes.Object047_Piano_0_2.geometry} material={materials.Decor_2} />
            <mesh geometry={nodes.Object047_Piano_0_3.geometry} material={materials.Decor_1} />
            <mesh geometry={nodes.Object047_Piano_0_4.geometry} material={materials.White_keys} />
            <mesh geometry={nodes.Object047_Piano_0_5.geometry} material={materials.Black_keys} />
          </group>
        </group>
      </group>
      <group position={[-16.277, 34.021, -32.501]} rotation={[-Math.PI / 2, 0, -1.55]} scale={0.498}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.379, 0.02, 0.729]} rotation={[1.745, 0, 0]} scale={0.12}>
            <group position={[3.439, 0.07, -0.012]} rotation={[-0.005, -0.042, -0.24]}>
              <mesh geometry={nodes.Object_5002_1.geometry} material={materials.body} />
              <mesh geometry={nodes.Object_5002_2.geometry} material={materials.red_plastic} />
              <mesh geometry={nodes.Object_5002_3.geometry} material={materials.power_button} />
              <mesh geometry={nodes.Object_5002_4.geometry} material={materials.slots} />
              <mesh geometry={nodes.Object_5002_5.geometry} material={materials.slots_2} />
              <mesh geometry={nodes.Object_5002_6.geometry} material={materials.display} />
              <mesh geometry={nodes.Object_5002_7.geometry} material={materials.logo} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-21.06, 35.741, -33.233]} rotation={[-Math.PI / 2, 0, 1.579]} scale={0.032}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0, -0.544]} rotation={[-Math.PI / 2, 0, 0]}>
            <mesh geometry={nodes.shelf_shelf_0.geometry} material={materials['shelf.001']} position={[-0.005, -0.62, 0]} />
          </group>
        </group>
      </group>
      <group position={[-19.619, 34.311, -33.228]} rotation={[-Math.PI / 2, 0, 2.228]} scale={0.069}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.003, 0.005, -0.001]}>
            <group position={[5.063, -0.542, -0.968]}>
              <mesh geometry={nodes['ayakkab��002_Material_0'].geometry} material={materials['Material.002']} position={[171.253, 35.208, -376.148]} rotation={[-1.274, 0.66, 0.73]} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-20.997, 35.255, -31.861]} rotation={[1.546, -0.027, -1.609]} scale={0.04}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.005, 0.004, 0.004]}>
            <group position={[0.005, 0.004, 0.004]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
              <mesh geometry={nodes.Torus002_Material001_0.geometry} material={materials['Material.005']} position={[-5.243, 114.721, 25.487]} rotation={[-0.039, 0.249, 2.291]} scale={0.251} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-21.216, 35.286, -33.212]} rotation={[0, -0.053, -Math.PI / 2]} scale={0.008}>
        <mesh geometry={nodes.Object_2002.geometry} material={materials['Scene_-_Root.001']} position={[16.57, 2.992, 56.797]} />
      </group>
      <group position={[-15.977, 33.614, -30.019]} rotation={[-Math.PI / 2, 0, 2.975]} scale={0.007}>
      <pointLight intensity={98.489} decay={2} color="#a568ff" position={[0, -140.056, 168.711]} rotation={[-Math.PI / 2, 0, -0.067]} />
        <group position={[0, -140.056, 168.711]} rotation={[-Math.PI, 0, 0]} scale={0.888}>
          <group position={[0, -0.028, -137.481]}>
            <mesh geometry={nodes.COPPER.geometry} material={materials.COPPER} />
            <mesh geometry={nodes.LAMP_SHADE.geometry} material={materials.LAMP_SHADE} />
            <mesh geometry={nodes.LIGHT_BULB.geometry} material={materials.EnvironmentAmbientLight} />
            <mesh geometry={nodes.RUBBER.geometry} material={materials.RUBBER} />
            <mesh geometry={nodes.STEEL.geometry} material={materials.STEEL} />
            <mesh geometry={nodes.STEEL_MATT_GREY.geometry} material={materials.STEEL_MATT_GREY} />
            <mesh geometry={nodes.STEEL_WHITE.geometry} material={materials.STEEL_WHITE} />
          </group>
        </group>
        <mesh geometry={nodes.FLOOR.geometry} material={materials.FLOOR} />
      </group>
      <group position={[-16.369, 34.25, -33.429]} rotation={[-Math.PI / 2, 0, 0]} scale={0.006}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0.068, 0.426, -1.366]} rotation={[-0.085, 0, -Math.PI / 2]} scale={12.137}>
            <mesh geometry={nodes.Object_4.geometry} material={materials['Material.010']} position={[2.642, -1.741, 3.612]} rotation={[0.085, 0.077, 1.469]} />
          </group>
        </group>
      </group>
      <group position={[-17.489, 33.08, -32.935]} rotation={[-Math.PI / 2, 0, -1.566]} scale={0.053}>
        <group position={[0, 10.591, 0]}>
          <mesh geometry={nodes.Plane001_carpet_0.geometry} material={materials.carpet} position={[1.503, 11.351, 0]} scale={[0.892, 0.799, 1]} />
        </group>
      </group>
      <group position={[-20.484, 35.51, -30.048]} rotation={[Math.PI / 2, 0, -1.807]} scale={0.032}>
        <group rotation={[-Math.PI, 0, 0]}>
          <mesh geometry={nodes.TeddyBearPT_Teddy_Inst_0.geometry} material={materials.Teddy_Inst} position={[21.217, -182.479, -40.97]} rotation={[0.77, 1.019, 2.329]} />
        </group>
      </group>
      <group position={[-17.516, 35.839, -28.265]} rotation={[1.572, 1.331, -Math.PI]} scale={0.053}>
        <mesh geometry={nodes.Object_2003.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        <mesh geometry={nodes.Object_3001.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        <mesh geometry={nodes.Object_4001.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        <mesh geometry={nodes.Object_5.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        <mesh geometry={nodes.Object_6.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        <mesh geometry={nodes.Object_7.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        <mesh geometry={nodes.Object_8.geometry} material={materials['portrait_femme_-_CleanUp_-_LowPoly_Material_u1_v1']} />
      </group>
      <group position={[-16.515, 34.026, -32.661]} rotation={[-Math.PI / 2, 0, 0]} scale={0.038}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[2.535, 0.216, 0.426]}>
            <group position={[-3.072, 0, 4.88]}>
              <mesh geometry={nodes.Object_7_1.geometry} material={materials['Black_Piece.001']} />
              <mesh geometry={nodes.Object_7_2.geometry} material={materials['Board.001']} />
              <mesh geometry={nodes.Object_7_3.geometry} material={materials['White_Piece.001']} />
            </group>
          </group>
        </group>
      </group>
      <group position={[-16.387, 34.073, -32.269]} rotation={[-1.742, -0.211, 0.762]} scale={0.019}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[3.893, 0, 0]} scale={[0.117, 0.11, 0.049]}>
            <mesh geometry={nodes.pCube1_blinn1_0.geometry} material={materials.blinn1} position={[0, 0, -0.001]} />
          </group>
          <group position={[3.899, 0, -0.134]} scale={[0.022, 0.111, 0.039]}>
            <mesh geometry={nodes.pCube2_blinn1_0.geometry} material={materials.blinn1} position={[-0.002, 0, 0.001]} />
          </group>
          <group position={[3.899, 0, -1.994]} scale={[0.022, 0.111, 0.233]}>
            <mesh geometry={nodes.pCube3_blinn1_0.geometry} material={materials.blinn1} position={[0.007, -0.001, 0]} />
          </group>
          <group position={[3.898, 0, -4.986]} scale={[0.06, 0.083, 0.076]}>
            <mesh geometry={nodes.pCube4_blinn1_0.geometry} material={materials.blinn1} position={[0.002, 0, 0.001]} />
          </group>
          <group scale={[1, 0.109, 0.072]}>
            <mesh geometry={nodes.pCube5_blinn1_0.geometry} material={materials.blinn1} position={[0, 0.001, -0.002]} />
          </group>
          <group position={[2.144, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.065}>
            <mesh geometry={nodes.pTorus1_lambert1_0.geometry} material={materials.lambert1} position={[0.002, -0.001, -0.002]} />
          </group>
          <mesh geometry={nodes.pSphere1_blinn1_0.geometry} material={materials.blinn1} position={[2.151, 0, 0.015]} scale={[1.635, 1.635, 0.236]} />
        </group>
      </group>
      <group position={[-21.031, 35.784, -32.712]} rotation={[-Math.PI / 2, 0, -1.759]} scale={1.558}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[37.858, 4.223, -37.858]} scale={0.631}>
            <mesh geometry={nodes.polySurface78_phong10_0.geometry} material={materials['phong10.001']} position={[20.34, -1.625, -3.877]} />
          </group>
        </group>
      </group>
      <group position={[-19.725, 34.023, -33.784]} rotation={[-2.323, -0.195, -2.939]} scale={0.643}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} position={[1.42, 1.227, 0.996]} rotation={[0.98, -0.56, 2.018]} scale={1.044} />
        </group>
      </group>
      <group position={[-21.168, 36.752, -30.584]} rotation={[-Math.PI, 1.516, -Math.PI]} scale={0.187}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_10001.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_7001.geometry} material={materials.Clock_face} />
          <mesh geometry={nodes.Object_8001.geometry} material={materials.Clock_Back} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Clock_hands} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_14.geometry} material={materials.Clock_hands} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Object_18.geometry} material={materials.Clock_hands} rotation={[Math.PI / 2, 0, 0]} />
          <mesh geometry={nodes.Object_24.geometry} material={materials.Clock_hands} rotation={[Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group position={[-21.015, 35.77, -32.739]} rotation={[-Math.PI / 2, 0, -1.875]} scale={0.007}>
        <mesh geometry={nodes.Object_2004.geometry} material={materials.blinn1SG} />
        <mesh geometry={nodes.Object_3002.geometry} material={materials.initialShadingGroup} />
      </group>
      <group position={[-21.025, 35.845, -32.915]} rotation={[-Math.PI / 2, 0, -2.116]} scale={0.072}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_0002.geometry} material={materials['Material.001']} />
          <mesh geometry={nodes.Object_0002_1.geometry} material={materials['Material.003']} />
        </group>
      </group>
      <group position={[-21.039, 35.775, -33.375]} rotation={[-Math.PI / 2, 0, 1.41]} scale={0.001}>
        <group position={[-0.002, -0.004, 0.006]}>
          <mesh geometry={nodes.Object_10002.geometry} material={materials.Grass} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.material_4} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_12.geometry} material={materials.Rock} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_13001.geometry} material={materials.Snow_ground} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_14001.geometry} material={materials.TreeSnow} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_15001.geometry} material={materials.Wood} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_2005.geometry} material={materials.Black} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_3003.geometry} material={materials.material} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_4003.geometry} material={materials['Glass.001']} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_5002.geometry} material={materials.Morcovka} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_6001.geometry} material={materials.Snow_ground} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_7002.geometry} material={materials.Mattexute} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_8002.geometry} material={materials.material_7} position={[-0.002, -0.004, 0.006]} />
          <mesh geometry={nodes.Object_9.geometry} material={materials['default']} position={[-0.002, -0.004, 0.006]} />
        </group>
      </group>
      <group position={[-16.739, 39.29, -40.14]} rotation={[-1.315, 0.239, -0.07]} scale={0.006}>
        <group position={[0.158, -19.255, 4.89]} rotation={[Math.PI / 2, 0, 0]}>
          <group position={[35.2, -144.873, -11.317]} rotation={[-0.253, 0.183, 0.981]}>
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Cup_HRBHPS_PinkCupSaucer_Cup_Mesh_0_lam002.geometry} material={materials['lambert5.001']} position={[-937.903, 62.785, 837.946]} scale={0.23} />
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Cup_HRBHPS_PinkCupSaucer_Cup_Mesh_0_lam003.geometry} material={materials['lambert5.001']} position={[-937.954, 62.847, 838.406]} scale={0.23} />
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Cup_HRBHPS_PinkCupSaucer_Cup_Mesh_0_lam004.geometry} material={materials['lambert5.001']} position={[-938.052, 62.999, 839.416]} scale={0.23} />
          </group>
          <group position={[31.748, 302.027, 495.475]} rotation={[1.857, -0.082, -0.538]}>
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Saucer_HR1BHPS_pinkCupSaucer_Saucer_Mes004.geometry} material={materials['lambert4.001']} position={[-780.153, 606.917, 621.081]} scale={0.23} />
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Saucer_HR1BHPS_pinkCupSaucer_Saucer_Mes005.geometry} material={materials['lambert4.001']} position={[-780.12, 606.996, 621.284]} scale={0.23} />
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Saucer_HR1BHPS_pinkCupSaucer_Saucer_Mes006.geometry} material={materials['lambert4.001']} position={[-780.062, 606.374, 620.655]} scale={0.23} />
            <mesh geometry={nodes.BHPS_PinkCupSaucer_Saucer_HR1BHPS_pinkCupSaucer_Saucer_Mes007.geometry} material={materials['lambert4.001']} position={[-779.814, 607.186, 622.472]} scale={0.23} />
          </group>
        </group>
      </group>
      <group position={[-18.586, 33.588, -28.744]} rotation={[-Math.PI / 2, 0, 0]} scale={0.181}>
        <mesh geometry={nodes.Object_10003.geometry} material={materials.black_st} />
        <mesh geometry={nodes.Object_11001.geometry} material={materials.st_red} />
        <mesh geometry={nodes.Object_12001.geometry} material={materials.st_leather} />
        <mesh geometry={nodes.Object_4004.geometry} material={materials.broun} />
        <mesh geometry={nodes.Object_5003.geometry} material={materials.green} />
        <mesh geometry={nodes.Object_6002.geometry} material={materials.green} />
        <mesh geometry={nodes.Object_7003.geometry} material={materials.black_st} />
        <mesh geometry={nodes.Object_8003.geometry} material={materials.black_st} />
        <mesh geometry={nodes.Object_9001.geometry} material={materials.black_st} />
      </group>
      <group position={[-20.4, 33.578, -28.958]} rotation={[-Math.PI / 2, 0, -2.365]} scale={1.06}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.Stool_Body_Bench_0.geometry} material={materials.Bench} position={[-113.615, 47.152, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Stool_Legs_Bench_0.geometry} material={materials.Bench} position={[-113.615, 40.68, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
        </group>
      </group>
      <group position={[-19.269, 36.204, -32.801]} rotation={[-Math.PI / 2, 0, 1.408]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[1, 1.133, 1]}>
            <mesh geometry={nodes.revolvedSurface1_blinn1_0.geometry} material={materials['blinn1.001']} position={[-0.001, -40.224, -190.979]} />
          </group>
        </group>
      </group>
      <group position={[-20.79, 33.588, -31.391]} rotation={[-Math.PI / 2, 0, 1.747]} scale={0.175}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.401, 8.831, 1.001]} rotation={[-Math.PI, 0, -3.003]} scale={[0.151, 0.837, 0.543]}>
            <mesh geometry={nodes.Object_4005.geometry} material={materials.Book_1} position={[-89.374, 7.65, 0.321]} />
            <mesh geometry={nodes.Object_5004.geometry} material={materials.Pages_2} position={[-89.374, 7.65, 0.321]} />
          </group>
          <group position={[-0.696, 8.729, 0.924]} rotation={[-Math.PI, 0, -3.003]} scale={[0.186, 0.733, 0.543]}>
            <mesh geometry={nodes.Object_7004.geometry} material={materials.Book_2} position={[-72.37, 8.739, 0.321]} />
            <mesh geometry={nodes.Object_8004.geometry} material={materials.Pages_2} position={[-72.37, 8.739, 0.321]} />
          </group>
          <group position={[-0.957, 8.527, 1.191]} rotation={[-Math.PI, 0, -3.003]} scale={[0.089, 0.541, 0.378]}>
            <mesh geometry={nodes.Object_28001.geometry} material={materials['Material.007']} position={[-150.706, 11.838, 0.46]} />
            <mesh geometry={nodes.Object_29.geometry} material={materials['Material.008']} position={[-150.706, 11.838, 0.46]} />
          </group>
          <group position={[-0.942, 1.5, 1.234]} rotation={[-Math.PI, 0.275, Math.PI / 2]} scale={[0.008, 0.729, 0.424]}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.Book_4} position={[-1418.263, -20.701, 10.275]} />
            <mesh geometry={nodes.Object_21001.geometry} material={materials.Side_book_4} position={[-1418.263, -20.701, 10.275]} />
          </group>
          <group position={[-0.942, 1.7, 1.234]} rotation={[-Math.PI, 0.275, Math.PI / 2]} scale={[0.008, 0.729, 0.424]}>
            <mesh geometry={nodes.Object_20.geometry} material={materials.Book_4} position={[-1418.263, -20.701, 10.275]} />
            <mesh geometry={nodes.Object_21001.geometry} material={materials.Side_book_4} position={[-1418.263, -20.701, 10.275]} />
          </group>
          <group position={[-1.047, 1.909, 1.166]} rotation={[0, 0.02, -Math.PI / 2]} scale={[0.009, 0.729, 0.562]}>
            <mesh geometry={nodes.Object_18001.geometry} material={materials.Book_5} position={[-1170.216, 21.542, 0.391]} />
          </group>
          <group position={[-1.047, 1.608, 1.166]} rotation={[0, -0.131, -Math.PI / 2]} scale={[0.093, 0.788, 0.562]}>
            <mesh geometry={nodes.Object_23.geometry} material={materials.Side_of_book_6} position={[-117.287, 19.752, -3.814]} />
            <mesh geometry={nodes.Object_24001.geometry} material={materials.Book_6} position={[-117.287, 19.752, -3.814]} />
          </group>
        </group>
      </group>
      <group position={[-20.393, 34.822, -33.78]} rotation={[-2.736, 0.167, 0.002]} scale={0.014}>
        <mesh geometry={nodes.Object_2006.geometry} material={materials.objcake} position={[1.083, -1.501, -6.461]} />
        <mesh geometry={nodes.Object_3004.geometry} material={materials.objcake} position={[-1.21, -0.985, -7.224]} />
        <mesh geometry={nodes.Object_4006.geometry} material={materials.objcake} position={[1.032, -1.494, -6.158]} />
      </group>
      <group position={[-19.606, 35.588, -29.132]} rotation={[-Math.PI / 2, -0.258, 1.472]} scale={0.038}>
        <mesh geometry={nodes.Object_10004.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_11002.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_2007.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_3005.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_4007.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_5005.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_6003.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_7005.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_8005.geometry} material={materials.defaultMat} />
        <mesh geometry={nodes.Object_9002.geometry} material={materials.defaultMat} />
      </group>
      <group position={[-18.764, 36.206, -28.186]} rotation={[1.573, -1.049, 0.002]} scale={0.02}>
        <group position={[7.279, -0.015, -12.674]}>
          <mesh geometry={nodes.Object_2008.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
          <mesh geometry={nodes.Object_3006.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
          <mesh geometry={nodes.Object_4008.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
          <mesh geometry={nodes.Object_5006.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
          <mesh geometry={nodes.Object_6004.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
          <mesh geometry={nodes.Object_7006.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
          <mesh geometry={nodes.Object_8006.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1']} />
        </group>
      </group>
      <group position={[-18.412, 35.596, -28.203]} rotation={[1.492, -1.048, -0.09]} scale={0.026}>
        <mesh geometry={nodes.Object_2009.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
        <mesh geometry={nodes.Object_3007.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
        <mesh geometry={nodes.Object_4009.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
        <mesh geometry={nodes.Object_5007.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
        <mesh geometry={nodes.Object_6005.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
        <mesh geometry={nodes.Object_7007.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
        <mesh geometry={nodes.Object_8007.geometry} material={materials['portrait_mary_douglas_-_CleanUp_-_LowPoly_Material_u1_v1.001']} />
      </group>
      <group position={[29.117, -344.334, -755.445]} rotation={[0.636, -0.087, 0.059]}>
        <mesh geometry={nodes.Object_2010.geometry} material={materials.material_0} position={[25.075, 732.758, 359.044]} rotation={[-1.088, 0.006, 0.109]} scale={0.002} />
        <mesh geometry={nodes.Object_3008.geometry} material={materials.material_0} position={[25.075, 732.758, 359.044]} rotation={[-1.088, 0.006, 0.109]} scale={0.002} />
        <mesh geometry={nodes.Object_4010.geometry} material={materials.material_0} position={[25.075, 732.758, 359.044]} rotation={[-1.088, 0.006, 0.109]} scale={0.002} />
        <mesh geometry={nodes.Object_5008.geometry} material={materials.material_0} position={[25.075, 732.758, 359.044]} rotation={[-1.088, 0.006, 0.109]} scale={0.002} />
      </group>
      <group position={[-19.461, 35.621, -28.818]} rotation={[-Math.PI / 2, 0, 0]} scale={0.016}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_6006.geometry} material={materials['Material.006']} position={[0, 2.611, 0]} scale={[1.341, 1.08, 1.341]} />
          <mesh geometry={nodes.Object_8008.geometry} material={materials.Material} position={[0.047, 12.145, -0.044]} />
          <mesh geometry={nodes.Object_4011.geometry} material={materials['Material.004']} position={[0, 6.876, 0]} scale={[1, 5.04, 1]} />
          <mesh geometry={nodes.Object_10005.geometry} material={materials['Flame.001']} position={[0.075, 12.831, -0.037]} scale={[0.292, 0.919, 0.292]} />
        </group>
      </group>
      <group position={[-20.469, 35.553, -29.764]} rotation={[-0.142, 0.998, 2.658]} scale={0.005}>
        <group position={[0, -0.002, 0.001]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0.031, -0.008, 0.016]}>
            <mesh geometry={nodes.aaleaf001_b001_leaf_0.geometry} material={materials.leaf} position={[16.234, -164.164, -1483.078]} rotation={[-Math.PI / 2, -0.088, 0]} scale={1000} />
            <mesh geometry={nodes.aaleaf001_b002_leaf_0.geometry} material={materials.leaf} position={[113.625, 35.121, -852.133]} rotation={[-1.183, -0.082, -3.108]} scale={764.975} />
            <mesh geometry={nodes.anemone_petal_001_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[35.391, 3743.762, -143.531]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.anemone_petal_002_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[960.203, 2620.801, 365.219]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.anemone_petal_003_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[-792.266, 2771.398, 188.789]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.anemone_petal_003_b002_petal_pink_0.geometry} material={materials.petal_pink} position={[111.328, 2218.645, 317.195]} rotation={[-0.753, -0.996, 1.295]} scale={450} />
            <mesh geometry={nodes.anemone_petal_004_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[-778.016, 2290.906, 311.648]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.anemone_petal_005_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[909.203, 3323.688, -270.227]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.anemone_petal_006_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[179.203, 1961.445, 306.766]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.anemone_petal_007_b001_petal_pink_0.geometry} material={materials.petal_pink} position={[-935.156, 3012.578, -267.727]} rotation={[-1.521, 0, 0]} scale={450} />
            <mesh geometry={nodes.stamens_inside_b001_stamens_inside_0.geometry} material={materials.stamens_inside} position={[14.906, 2789.105, -98.258]} rotation={[-1.892, 0, 0]} scale={450} />
            <mesh geometry={nodes.stamens_outside003_stamens_outside_0.geometry} material={materials.stamens_outside} position={[13.719, 2789.141, -114.211]} rotation={[-1.892, 0, 0]} scale={450} />
            <mesh geometry={nodes.stem001_stem_0.geometry} material={materials.stem} position={[30.688, -1039.594, -842.07]} rotation={[-1.484, 0, 0]} scale={500} />
          </group>
        </group>
      </group>
      <group position={[-13.357, 17.002, -33.68]} rotation={[-Math.PI / 2, 0, -1.452]} scale={347.018}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, -1.236, 0]} scale={[9.845, 0.357, 4.91]}>
            <mesh geometry={nodes.home_1.geometry} material={materials.lambert3} onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera('back');
    } else {
      setDefaultCamera('back1');
    }
 }} 
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
            <mesh geometry={nodes.home_2.geometry} material={materials.lambert5} />
            <mesh geometry={nodes.home_3.geometry} material={materials.lambert2} />
          </group>
        </group>
      </group>
      <PerspectiveCamera makeDefault={defaultCamera === 'back'}  far={1000} near={0.1} fov={37} position={[-10.811, 36.033, -35.709]} rotation={[-2.912, 0.966, 2.948]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'back2'} far={1000} near={0.1} fov={105.895} position={[-18.571, 34.7, -34.439]} rotation={[-2.796, 1.035, 2.836]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'back1'}  far={1000} near={0.1} fov={22.895} position={[-9.811, 36.033, -37.709]} rotation={[-2.912, 0.966, 2.948]} scale={0.431} />
      
      <PerspectiveCamera makeDefault={defaultCamera === 'back3'} far={1000} near={0.1} fov={35} position={[-9.811, 36.033, -34.709]} rotation={[-2.912, 0.966, 2.948]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'com1'} far={1000} near={0.1} fov={25.895} position={[-18.571, 35.176, -34.439]} rotation={[-2.796, 1.035, 2.836]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'com'} far={1000} near={0.1} fov={65.895} position={[-18.571, 35.176, -34.439]} rotation={[-2.796, 1.035, 2.836]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'piano'} far={1000} near={0.1} fov={52.895} position={[-20, 35.431, -33.72]} rotation={[-3.124, -0.299, -3.141]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'piano1'} far={1000} near={0.1} fov={22.895} position={[-20.472, 35.431, -33.72]} rotation={[-3.124, -0.299, -3.141]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'camera'}  far={100} near={0.1} fov={60.895} position={[48.704, -1.084, 17.202]} rotation={[0.443, 0.841, -0.34]} scale={1.825} />
      <PerspectiveCamera makeDefault={defaultCamera === 'camera1'}  far={100} near={0.1} fov={45.895} position={[48.704, -1.084, 17.202]} rotation={[0.443, 0.841, -0.34]} scale={1.825} />
      <PerspectiveCamera makeDefault={defaultCamera === 'lap1'}  far={1000} near={0.1} fov={22.895} position={[-15.301, 34.406, -31.875]} rotation={[-0.716, 1.255, 0.687]} scale={0.431} />
      <PerspectiveCamera makeDefault={defaultCamera === 'lap'}  far={1000} near={0.1} fov={72.895} position={[-15.301, 34.406, -31.875]} rotation={[-0.716, 1.255, 0.687]} scale={0.431} />
      <mesh geometry={nodes.room.geometry} material={materials['material.003']} position={[-17.721, 33.59, -32.58]} scale={[3.841, 5.508, 4.823]} />

      <mesh geometry={nodes.computer.geometry} material={nodes.computer.material} position={[-20.994, 34.863, -33.206]} rotation={[0, 0, -1.51]} scale={0.127} onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera(prevCamera => prevCamera === 'com' ? 'back3' : 'com');
    } else {
      setDefaultCamera(prevCamera => prevCamera === 'com1' ? 'back1' : 'com1');
    }
 }} 
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
      <mesh geometry={nodes.laptop.geometry} material={nodes.laptop.material} position={[-16.648, 34.192, -32.041]} rotation={[0.013, 0.246, -1.387]} scale={0.074} onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera(prevCamera => prevCamera === 'lap' ? 'back2' : 'lap');
    } else {
      setDefaultCamera(prevCamera => prevCamera === 'lap1' ? 'back1' : 'lap1');
    }
 }} 
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
      <mesh geometry={nodes.protobyte.geometry} material={nodes.protobyte.material} position={[-18.444, 36.222, -28.124]} scale={[0.13, 0.165, 0.13]} onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera(prevCamera => prevCamera === 'piano' ? 'back' : 'piano');
    } else {
      setDefaultCamera(prevCamera => prevCamera === 'piano1' ? 'back1' : 'piano1');
    }
 }} 
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
      <mesh geometry={nodes['big-frame'].geometry} material={nodes['big-frame'].material} position={[-17.484, 35.901, -28.33]} rotation={[-1.612, 0, 0]} scale={0.215}  onClick={() => {
    if (windowWidth < 768) {
      setDefaultCamera(prevCamera => prevCamera === 'piano' ? 'back' : 'piano');
    } else {
      setDefaultCamera(prevCamera => prevCamera === 'piano1' ? 'back1' : 'piano1');
    }
 }} 
 onPointerOver={() => document.body.style.cursor = 'pointer'}
 onPointerOut={() => document.body.style.cursor = 'auto'}/>
    </group>
  )
}

useGLTF.preload('/maram03.gltf')
